# Generated by Django 2.2.12 on 2020-06-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('name', models.CharField(help_text='Enter profile name', max_length=70)),
                ('national_id', models.BigIntegerField(help_text='Enter National ID', primary_key=True, serialize=False)),
                ('age', models.PositiveSmallIntegerField(help_text='Enter age')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.CharField(max_length=100)),
                ('academic_status', models.CharField(max_length=50)),
                ('social_status', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('driving_license', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], help_text='add if thier driving license or not', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_name', models.CharField(help_text='Enter username', max_length=8, primary_key=True, serialize=False)),
                ('password', models.CharField(help_text='Enter password', max_length=30)),
            ],
        ),
    ]
