# Generated by Django 2.2.12 on 2020-06-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driving_license',
            fields=[
                ('traffic_police_area', models.CharField(max_length=30)),
                ('quadruple_name', models.CharField(max_length=100)),
                ('national_id', models.BigIntegerField(help_text='Enter National ID', primary_key=True, serialize=False)),
                ('phone_number', models.IntegerField(help_text='Enter Phone Number')),
                ('address', models.CharField(help_text='Enter address', max_length=100)),
                ('date_of_birth', models.DateField(help_text='Enter Date of Birth')),
            ],
        ),
        migrations.CreateModel(
            name='Idcard',
            fields=[
                ('national_id', models.BigIntegerField(default=123456789, help_text='Enter National ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter First Name', max_length=15)),
                ('father_name', models.CharField(help_text='Enter Father Complete Name', max_length=100)),
                ('mother_name', models.CharField(help_text='Enter Mother Name', max_length=100)),
                ('religion', models.CharField(choices=[('muslim', 'مسلم'), ('Christian', 'مسيحي'), ('Godless', 'بلا ديانة')], max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('social_status', models.CharField(choices=[('married', 'متزوج'), ('Widowed', 'أرمل'), ('divorced', 'مطلق'), ('single', 'أعزب')], max_length=50)),
                ('governorate', models.CharField(default='mansoura', max_length=15)),
                ('department', models.CharField(default='45', max_length=30)),
                ('village', models.CharField(default='45', max_length=30)),
                ('building_number', models.IntegerField(default=1)),
                ('street', models.CharField(default='45', max_length=30)),
                ('floor_number', models.IntegerField(default=1)),
                ('aprtment', models.IntegerField(default=1)),
                ('phone_number', models.IntegerField(default=10022334455, help_text='Enter Phone Number')),
                ('residential_pool', models.CharField(default='45', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(help_text='Enter profile name', max_length=70)),
                ('national_id', models.BigIntegerField(help_text='Enter National ID', primary_key=True, serialize=False)),
                ('age', models.PositiveSmallIntegerField(help_text='Enter age')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.CharField(max_length=100)),
                ('academic_status', models.CharField(max_length=50)),
                ('social_status', models.CharField(choices=[('married', 'متزوج'), ('Widowed', 'أرمل'), ('divorced', 'مطلق'), ('single', 'أعزب')], max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('driving_license', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], help_text='add if thier driving license or not', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('national_id', models.BigIntegerField(help_text='Enter National ID', primary_key=True, serialize=False)),
                ('password', models.CharField(help_text='Enter password', max_length=30)),
            ],
        ),
    ]
