# Generated by Django 2.2.12 on 2020-06-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcard',
            name='photograph',
            field=models.ImageField(default='/graduationproject/media/default.jpg', upload_to='media'),
        ),
    ]
