# Generated by Django 2.2.12 on 2020-06-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_idcard_photograph'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birth_certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('nationality', models.CharField(default='Egyptian', max_length=30)),
                ('religion', models.CharField(choices=[('muslim', 'مسلم'), ('Christian', 'مسيحي'), ('Godless', 'بلا ديانة')], max_length=30)),
                ('birth_place', models.CharField(default='Egypt', max_length=40)),
                ('date_of_birth', models.DateField(help_text='Enter Date of Birth')),
                ('father_quadruple_name', models.CharField(max_length=100)),
                ('father_nationality', models.CharField(default='Egyptian', max_length=30)),
                ('father_religion', models.CharField(choices=[('muslim', 'مسلم'), ('Christian', 'مسيحي'), ('Godless', 'بلا ديانة')], max_length=30)),
                ('mother_quadruple_name', models.CharField(max_length=100)),
                ('mother_nationality', models.CharField(default='Egyptian', max_length=30)),
                ('mother_religion', models.CharField(choices=[('muslim', 'مسلم'), ('Christian', 'مسيحي'), ('Godless', 'بلا ديانة')], max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
